name: Build IPK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build IPK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget qemu-utils
          export TERM=xterm

      - name: Download resources
        run: |
          echo "Download SDK"
          curl -L https://downloads.openwrt.org/releases/23.05.4/targets/x86/64/openwrt-sdk-23.05.4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -o sdk.tar.xz
          mkdir openwrt-sdk
          tar -xf sdk.tar.xz -C openwrt-sdk --strip-components=1
          echo "Clone IPK"
          git clone https://github.com/animegasan/luci-app-speedtest openwrt-sdk/package/luci-app-speedtest

      - name: Set up SDK feeds
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build IPK from Makefile
        run: |
          cd openwrt-sdk
          make defconfig
          make package/luci-app-speedtest/compile V=s
          ls bin/packages/x86_64/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0'    # Kamu bisa mengubah ini ke versi yang diinginkan
          release_name: 'Release v1.0.0'
          body: "Build dari IPK luci-app-speedtest"
          draft: false
          prerelease: false

      - name: Upload IPK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: openwrt-sdk/bin/packages/x86_64/luci-app-speedtest.ipk
          asset_name: luci-app-speedtest.ipk
          asset_content_type: application/octet-stream
