name: Build IPK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build IPK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Download resources
        run: |
          curl -L https://downloads.openwrt.org/releases/23.05.4/targets/x86/64/openwrt-sdk-23.05.4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -o sdk.tar.xz
          mkdir sdk && tar -xf sdk.tar.xz -C sdk --strip-components=1
          git clone https://github.com/animegasan/luci-app-speedtest sdk/package/luci-app-speedtest

      - name: Set up SDK feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build IPK from Makefile
        run: |
          cd sdk
          make defconfig
          rm -rf feeds/luci/contrib/package/csstidy
          sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
          sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config
          export TERM=xterm
          ls -l package/luci-app-speedtest/root/usr/share/speedtest/schedule
          make package/luci-app-speedtest/compile
          IPK_PATH=$(find bin/packages/x86_64/base/ -name 'luci-app-*.ipk')
          IPK_NAME=$(basename $IPK_PATH)
          echo "IPK_PATH=sdk/$IPK_PATH" >> $GITHUB_ENV
          echo "IPK_NAME=$IPK_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0'    # Kamu bisa mengubah ini ke versi yang diinginkan
          release_name: 'Release v1.0.0'
          body: "Build dari IPK luci-app-speedtest"
          draft: false
          prerelease: false

      - name: Upload IPK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.IPK_PATH }}
          asset_name: ${{ env.IPK_NAME }}
          asset_content_type: application/octet-stream
